ARG ELASTIC_STACK_VERSION

FROM docker.elastic.co/beats/heartbeat:${ELASTIC_STACK_VERSION}

USER root

COPY ./certificate/elastic-ca.crt.pem ./certificate/elastic.crt.pem ./certificate/elastic.key.pem ./config/heartbeat.yml  /usr/share/heartbeat/

RUN chmod 644 /usr/share/heartbeat/heartbeat.yml
