ARG ELASTIC_STACK_VERSION

FROM docker.elastic.co/beats/filebeat:${ELASTIC_STACK_VERSION}

USER root

COPY ./certificate/elastic-ca.crt.pem ./certificate/elastic.crt.pem ./certificate/elastic.key.pem ./config/filebeat.yml /usr/share/filebeat/

RUN chmod 644 /usr/share/filebeat/filebeat.yml
