node.name: '${HOSTNAME}'
network.host: '0.0.0.0'
cluster.name: 'es-docker-cluster'
cluster.initial_master_nodes: 'elasticsearch01,elasticsearch02,elasticsearch03'
bootstrap.memory_lock: true
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.keystore.type: 'PKCS12'
xpack.security.transport.ssl.verification_mode: 'certificate'
xpack.security.transport.ssl.keystore.path: 'elastic-certificates.p12'
xpack.security.transport.ssl.keystore.password: '${ELASTIC_PASSWORD}'
xpack.security.transport.ssl.truststore.path: 'elastic-certificates.p12'
xpack.security.transport.ssl.truststore.password: '${ELASTIC_PASSWORD}'
xpack.security.transport.ssl.truststore.type: 'PKCS12'
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.keystore.path: 'http.p12'
xpack.security.http.ssl.keystore.password: '${ELASTIC_PASSWORD}'
